export const APP_ROUTES = {
  ROOT: "/",
  BATTER: "batter",
  COACH: "coach",
  GAME: "game",
  HOME: "home",
  AUTH: { LOGIN: "login" },
  PHASE: "phase",
  PITCHER: "pitcher",
  PLAYER: "player",
  POSITION: "position",
  PROVINCE: "province",
  REPORT: {},
  STADIUM: "stadium",
  TEAM: "team",
  USER: "user",
} as const;
